### ISSUE TITLE
Feature Request: Improvements to tables

### ISSUE THREAD

**Issue by spiritualgeek** [chrisgrieser/shimmering-focus#117]
### Feature Requested

Not really a bug but:

Tables (not dataview ones) seem to always have evenly spaced columns, no matter whether a particular column has longer text

There appears to be no automatic resizing happening. Could this be changed?

I'd also be very appreciative if you'd consider exposing the following to the Style settings plugin:
1. A maximum size that any column can be 
2. Max font size for <td>
3. Max font size for <th>
4. Options to minimize (or completely remove) padding

Dataview tables should work in the same fashion and this should be consistent between reading view and live preview modes (i.e. look exactly the same)

Thanks for a wonderful theme

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by spiritualgeek** [comment]
Would be nice if you could implement at some stage, but I'm closing this as I'm actively using another theme for now

**Comment by chrisgrieser** [comment]
- [ ] 🏴‍☠️ from @tingmelvin 
![image](https://user-images.githubusercontent.com/73286100/161526438-f947facb-1715-4396-98d4-0077180d5d40.png)

**Comment by tingmelvin** [comment]
> - [ ] 🏴‍☠️ from @tingmelvin 
> ![image](https://user-images.githubusercontent.com/73286100/161526438-f947facb-1715-4396-98d4-0077180d5d40.png)
> 

actually, that's 🏴‍☠️ from @SlRvb

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
