### ISSUE TITLE
[Bug]: support for lapel plugin

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#125]
### Bug Description

The plugin : https://github.com/liamcain/obsidian-lapel

The headings don't align with the icon

### Relevant Screenshot

https://user-images.githubusercontent.com/38974541/158782438-9bfcd72e-b19e-4b65-bf9c-e643b2af98fa.mov

### To Reproduce

1. activate live preview
2. make a heading

### Obsidian Version

0.13.33

### Installer Version

0.13.31

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
