### ISSUE TITLE
It doesn't render well with Focus Mode plugin

### ISSUE THREAD

**Issue by jsmm** [chrisgrieser/shimmering-focus#15]
Hi. Just lo let you know that this theme doesn't work well with [Focus Mode plugin](https://github.com/ryanpcmcquen/obsidian-focus-mode). I think this bug happened only in the last releases of your theme.

**Comment by chrisgrieser** [comment]
Could you maybe share a screenshot or a screen recording whats wrong? 

Especially when it only happened with the latest release, it should be easy to fix.

**Comment by chrisgrieser** [comment]
well, that the disappearance of the ribbon (the left menu bar) and the title bar isn't a bug, but a feature of the theme. See the section on [minimalism](https://github.com/chrisgrieser/shimmering-focus#features--design-principles). As described there, you can re-enable both of them via the Style Settings Plugin. 

However, both have been included since the very first release of the theme, so I am not sure what changed for you?

**Comment by jsmm** [comment]
I guess I was switching themes to update and had forgotten about this feature. Thanks for reminding me about it.
