### ISSUE TITLE
Contribution: File View near traffic icons

### ISSUE THREAD

**Issue by MSzturc** [chrisgrieser/shimmering-focus#157]
### Type of Contribution

Implementing a feature request

### Description

Moves the fileView Toolbar near the traffic lights on macos, which makes the layout even slimmer

```
.mod-macos:not(.show-titlebar) .mod-left-split .workspace-tabs:nth-child(3) .workspace-tab-header-container.workspace-tab-header-container.workspace-tab-header-container {
    height: 32px;
    padding: 3px 38px 5px;
}
```

**Comment by chrisgrieser** [comment]
Hi, thanks for the contribution!

your example is actually how I implemented it previously, however, it seems for some screen resolutions, this causes a problem, which is why I increased the size slightly (e.g. #135).

Adding the snippet would mean causing visual overlaps for some users, which is why I can't add this one, unfortunately (see #135 for an example).
