### ISSUE TITLE
Feature Request: Show static markers in Reading Mode

### ISSUE THREAD

**Issue by HideOnLie** [chrisgrieser/shimmering-focus#158]
### Feature Requested

hope can add the markers in Reading Mode. 
In my scenario, when I read my own notes, I prefer to open in the reading mode. This can prevent me from accidentally modifying. But in reading mode, these titles are not so easy to distinguish.  
BTW, the theme is great~

### Relevant Screenshot

in live preview：
![image](https://user-images.githubusercontent.com/51672711/166451674-ce019dd7-3d93-403a-bf1b-9dbde987e173.png)

in reading mode：
![image](https://user-images.githubusercontent.com/51672711/166451489-e89c9872-3954-4515-94e0-f48a6ded0fe3.png)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
