### ISSUE TITLE
[Bug]: Unresolved Links Indicator Placement in Callouts blocks content (with Admonitions Plugin)

### ISSUE THREAD

**Issue by MalignantCarp** [chrisgrieser/shimmering-focus#165]
### Bug Description

When using a callout, if there is an unresolved link, the unresolved link indicator is covering some of the content. This seems to only happen when using the Admonitions plugin, so I am guessing some conflict in the resulting CSS.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/93364935/167040459-a079d1c2-ffb5-47af-bdc7-951c463af1a6.png)

### To Reproduce

With the Admonitions plugin (current version 9.0.2), insert the following into a new Markdown file:
```
> [!bug] Callouts with unresolved links are buggy
> Line of a callout with an [[unresolved link]]

> [!question] Callout titles with an [[unresolved link]] aren't
> Interestingly, these are not problematic.
```

### Obsidian Version

0.14.9

### Installer Version

0.14.6

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
