### ISSUE TITLE
[Bug]: Sliding Panes on Mobile does not enable Headers

### ISSUE THREAD

**Issue by EdJoJob** [chrisgrieser/shimmering-focus#170]
### Bug Description

When enabling Sliding Panes on Desktop, the headers of the Panes are enabled automatically. This does not happen on Mobile.

This results in the header space being rendered as transparent, with the Edit/Reading mode switch button rendered in the header location, but with the disabled header view.

### Relevant Screenshot

![Screenshot_20220520-115906_Obsidian](https://user-images.githubusercontent.com/1487851/169433679-f852a5d6-e56b-412a-bab3-cc5e2c5e4d5d.jpg)

### To Reproduce

Requires:
- Sliding Panes
- Style Settings
- Android App

SlidingPanes settings:
- Enable sliding panes: Enabled
- Smooth Animation: Enabled
- Leaf Auto Width: Disabled
- Leaf Width: 400
- Toggle Rotated Headers: Enabled
- Swap Rotated Header Direction: Disabled
- Header Text Direction: Mixed
- Toggle Stacking: Enabled
- Spine Width: 32

1. Open two panes with vertical split
2. Slide right pane over left one
3. Header gap rendered, without header content

### Obsidian Version

1.2.0 (50) API v0.14.2

### Installer Version

na

### Font Size

15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [X] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
