### ISSUE TITLE
[Bug]: Math in headings appears before the heading indicator

### ISSUE THREAD

**Issue by zcysxy** [chrisgrieser/shimmering-focus#171]
### Bug Description

Math in a heading, like `## $\sigma$-Algebra` appears before the heading indicator.

### Relevant Screenshot

Cursor on the same line:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/48207708/170854265-85e63ecc-ed88-45de-900f-d3bbe3129860.png">

Cursor moved away:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/48207708/170854274-c428c7c3-0646-44dc-9eb3-c58e7405a410.png">

### To Reproduce

Type `## $\sigma$-Algebra`.

### Obsidian Version

0.14.15

### Installer Version

0.14.15

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
