### ISSUE TITLE
[Bug]: Unresolved link in header results in Header Level not being displayed before header text when in Live Preview mode

### ISSUE THREAD

**Issue by Gewerd-Strauss** [chrisgrieser/shimmering-focus#177]
### Bug Description

Assume we have a header 

        # CRISPR-Cas9
    A tool for introducing DNA at specfic locations into host DNA

Right now, this is gonna be displayed as seen in image 1.
And now we want to make the header a link, so we do the following

        # [[CRISPR-Cas9]]
    A tool for introducing DNA at specfic locations into host DNA

which results in image 2. 

### Relevant Screenshot

1: ![grafik](https://user-images.githubusercontent.com/80548781/175773607-00424ad8-53a5-4034-b55d-c6148e8edee4.png)

2: ![grafik](https://user-images.githubusercontent.com/80548781/175773651-e89cba05-7953-4c83-9ecb-578663c79975.png)

### To Reproduce

1. Make a header like below:
```
# CRISPR-Cas9
    A tool for introducing DNA at specfic locations into host DNA

```

2. Check that the header level is displayed before the beginning of the header
3. Convert the Header into a link like below

```
# [[CRISPR-Cas9]]
    A tool for introducing DNA at specfic locations into host DNA

```
4. Make sure the linked-to file does not exist
5.  Notice the missing Header-level before the beginning of the header, while the "missing-file-X" is displayed within the 

### Obsidian Version

0.14.15

### Installer Version

0.14.15

### Font Size

14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of Shimmering Focus. This means:

A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten Shimmering Focus.
As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.
Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of Shimmering Focus, please comment here and I will re-open it. 🙂
