### ISSUE TITLE
Feature Request: if the dim degree can be adjusted in style settings

### ISSUE THREAD

**Issue by oldwinter** [chrisgrieser/shimmering-focus#179]
### Feature Requested

Do not dim Inactive Panes
Also affects popovers from the Hover Editor Plugin.

this feature is usefull. if the dim degree can be adjusted in style settings. it will be wonderful . just like macos app: hazeover

### Relevant Screenshot

<img width="260" alt="image" src="https://user-images.githubusercontent.com/8112159/177033501-dde0bdaa-c926-4a6f-b638-d1c4d03860ec.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/8112159/177033541-01a4ca6b-cac1-4106-9cdf-97764f14b6ef.png">

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
