### ISSUE TITLE
Feature Request: Tighten layout in tag and file explorer panes

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#185]
### Feature Requested

I would like the option to tighten up spacing in the tag and file explorer panes. I much prefer the compact styling demonstrated by the recent files and file tree alternatives panels, and would appreciate a consistent look.

### Relevant Screenshot

File explorer:
![image](https://user-images.githubusercontent.com/42705243/178732392-154247b7-430f-4d55-b7d7-861e109afb1e.png)

Tag pane:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/42705243/178732488-4710e912-ef16-4e86-8a4a-6ae42cab36ef.png">

Recent files:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/42705243/178732575-54d76f1b-db6a-4c9c-b437-23c89e076958.png">

File tree alternative:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/42705243/178732644-0fe1ca3f-4737-4524-ab70-9346d15553b1.png">

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
