### ISSUE TITLE
[Bug]: Citation syntax renders incorrectly in reading mode

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#188]
### Bug Description

When using the double-blockquote citation syntax to create a citation, the effect is rendered as expected in source and live preview modes, but incorrectly in reading mode.

### Relevant Screenshot

Source:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/42705243/178735493-98077756-bc71-47bd-9385-125c83c5af21.png">

Live Preview:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/42705243/178735550-4811b9a7-8e70-4440-9b64-05c3e3f5e0a8.png">

Reading:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/42705243/178735644-d5d267cd-b489-4289-9448-809befc5a341.png">

### To Reproduce

Create a blockquote with citation using the double-blockquote syntax, e.g.:

```
> this is a quote by me
>> Dan O'Leary
```

Observe the rendering behavior described above.

### Obsidian Version

0.15.6

### Installer Version

0.15.6

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
