### ISSUE TITLE
Feature Request: Hide lines separating embeds

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#189]
### Feature Requested

I would like to be able to hide the separating lines that currently surround embeds.

This could be a style settings option or added to the `clean-embeds` css class. Since these lines are present in the default theme it may make more sense to make it a style settings option. Either would work for me,

### Relevant Screenshot

<img width="622" alt="image" src="https://user-images.githubusercontent.com/42705243/178760535-f9fe78e1-ef07-46a6-bd84-3cd263c9ebea.png">

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
