### ISSUE TITLE
[Bug]: Supercharged links built-in styling issues...

### ISSUE THREAD

**Issue by olearydj** [chrisgrieser/shimmering-focus#190]
### Bug Description

I've noticed some issues when trying out the built-in styling for supercharged links.
1. seedling notes have the emoji appended rather than prepended as documented (reading mode), except in live preview or source modes
2. icon for templater is a blank page not the star / snowflake emoji as documented
3. no emoji is added for kanban boards
4. no emoji is added for files with `cssclass: writing` in the yaml data
5. no emoji is added for files with a `title` key in the yaml data
6. the documentation is unclear about how to designate a file a Literature Note for the purpose of styling

### Relevant Screenshot

Result (reading):
<img width="365" alt="image" src="https://user-images.githubusercontent.com/42705243/178858823-c9590ec3-bdb2-4e3a-a0fe-f6310cab6222.png">

Result (live preview):
<img width="316" alt="image" src="https://user-images.githubusercontent.com/42705243/178859483-a4aa60f7-59da-45d6-8d94-ad762256852d.png">

Result (source mode):
<img width="326" alt="image" src="https://user-images.githubusercontent.com/42705243/178859460-dc8de7a3-e446-4ecb-a31d-31c4628d882d.png">

FIles:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/42705243/178858676-243bfa5c-1ba1-4cba-9008-4ac94c6f2cc1.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/42705243/178858715-313daba5-e1f8-4a66-9993-bd3dd3441d6a.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/42705243/178858758-35eeb91d-5af6-4430-9bc8-9543d5b00c80.png">

<img width="390" alt="image" src="https://user-images.githubusercontent.com/42705243/178858794-26b9ffcf-2320-49ae-9bb0-d92ce098a97b.png">

### To Reproduce

Create test files as pictured above and observe corresponding results.

### Obsidian Version

0.15.6

### Installer Version

0.15.6

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
