### ISSUE TITLE
[Bug]: (minor) Application title displaying incorrectly

### ISSUE THREAD

**Issue by gala8y** [chrisgrieser/shimmering-focus#192]
### Bug Description

Application title bar does not correctly display 'document name - vault name - obsidian version'.

### Relevant Screenshot

![window title with note opened](https://user-images.githubusercontent.com/1263605/179359049-89592b3e-c3fc-4fce-bfb8-3186393658aa.png)
window title with note opened

![window title with no note opened](https://user-images.githubusercontent.com/1263605/179359046-f3724fdb-dae4-4a6c-911d-adfb3f02282e.png)
window title with no note opened

### To Reproduce

n/a

### Obsidian Version

0.15.6

### Installer Version

0.14.15

### Font Size

17

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [ ] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
