### ISSUE TITLE
Feature Request: Window Handle for Popout Windows

### ISSUE THREAD

**Issue by zcysxy** [chrisgrieser/shimmering-focus#193]
### Feature Requested

I wish to move popout windows around. In other themes, I can drag them via the title bar, but I think Shimmering Focus hides the handle. Therefore I think it would be better to have a window handle for popout windows.

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂

**Comment by chrisgrieser** [comment]
This issue is more than 3 years old. Please create a new bug report, the form asks for various info I'd need to be able to do anything.
