### ISSUE TITLE
[Bug]: Checking "No File Icon" in style settings add strange string to file name in file explorer.

### ISSUE THREAD

**Issue by nachiketa3299** [chrisgrieser/shimmering-focus#197]
### Bug Description

# Checking "No File Icon" in style settings add strange string to file name in file explorer.

As what is looks like. 
But actually it doesn't change the actual file name.
When I go to file, it has correct file name, but **only** the name displayed in file explorer are changed.
(Not in the recent file(plugin) starred file, or the result of file search... )

Especially, the strange string "setting"is added to the filename.
For example if I have file named `Obsidian Index`, and if I turn on the "No File Icon" setting, then it goes to `settingObsidian Index`.

I think it is scss/css related problem. 

This is so annoying.

### Relevant Screenshot

<img width="172" alt="스크린샷 2022-07-26 14 29 37" src="https://user-images.githubusercontent.com/46415457/180930359-347927e6-747d-44ea-a3cb-9422ee6f219c.png">

Strange string "setting"is added to the filename.
Does not affect real file name.

<img width="214" alt="스크린샷 2022-07-26 14 30 17" src="https://user-images.githubusercontent.com/46415457/180930436-2c9e0449-c0fd-4eff-be8a-64d6934409b3.png">

### To Reproduce

My current Obsidian version is **v0.15.8** (Installer version: **v0.15.6**)

### Installed Plugins

- Calendar
- Dataview
- Icon Folder
- Kanban
- Recent Files
- Sliding Panes (Andy's Mode)
- Style Settings
- Templater

### Settings to reproduce this problem

1. Install "Style Settings" Plugin
2. Go to _Settings>Style Settings>User Interface>File Explorer_
3. Check the setting **File Explorer: No File Icons**

### Obsidian Version

0.15.8

### Installer Version

0.15.6

### Font Size

20

### Which editor are you using?

- [X] New Editor
- [x] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
