### ISSUE TITLE
Feature Request: Mobile Reading Mode width control

### ISSUE THREAD

**Issue by Cateroo** [chrisgrieser/shimmering-focus#199]
### Feature Requested

Ability to modify/expand the width of the text in reading mode on mobile screent currently doesn't exist. On mobiles, the text gets squished and there are gaps in the left and right margins that could otherwise be used to expand the text space and make reading (especially with nested lists) easier. 

### Relevant Screenshot

![Screenshot_20220823-114534](https://user-images.githubusercontent.com/80290663/186148358-d0d350f2-eaf5-4e3c-9e24-5499715d6f67.jpg)

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
