### ISSUE TITLE
Feature Re-Creation: Old-style headers

### ISSUE THREAD

**Issue by Daantjerrr** [chrisgrieser/shimmering-focus#211]
### Feature to be re-created

The old-style headers (with 'boxes' surrounding them) were really helpful when working with longer notes. I'd love to have them back.

### Relevant Screenshot

![afbeelding](https://user-images.githubusercontent.com/16157534/191592837-df2a8521-f6e5-41e3-98c5-b8e2ee8964a8.png)

### Checklist

- [X] I updated to the latest version of the theme and checked that the feature has not been re-created yet.

**Comment by Gewerd-Strauss** [comment]
I will add to this that having the headerlevel H1-H6 in the gutter of a header is a tremendous advantage for me when spotting headers and their relation to each other. Size-differences can/could be configured I believe, but the headerlevel was unambiguous. It was among the most helpful aspects of the theme, because due to my structure and workload I often require a lot of headers n a specific hierarchy.

**Comment by Gewerd-Strauss** [comment]
Bumping this as it is still relevant.

**Comment by Gewerd-Strauss** [comment]
bump, see comment above

**Comment by chrisgrieser** [comment]
feature is back in latest release :)

(Sorry for the long wait, I simply have too many projects I maintain 😅 )

**Comment by Daantjerrr** [comment]
This is awesome, thank you so much! (also, are you the Obisidian-quardo guy? Really cool! I've been using Obisidian for some research myself so I will probably check it out once I want to code something in the future)

**Comment by chrisgrieser** [comment]
yep, I also published Quadro :)

Feel free to post in the [Quadro discussions](https://github.com/chrisgrieser/obsidian-quadro/discussions) if you want to have a chat about it at some point in the future.
