### ISSUE TITLE
Dataview inline annotations act like Pandoc citations

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#26]
look at the first task - it only has one inline metadata key, which is green. the second task has two inline metadata keys, and one is blue, and the other is grey. is there anything you could do with this? just nice-to-have. 

![image](https://user-images.githubusercontent.com/59067099/135760577-15783f22-7934-4892-bd38-c418784802a5.png)

**Comment by chrisgrieser** [comment]
that's unfortunately not something I can change, since the underlying issue is that Obsidian recognizes the first are as bare link (which I repurpose to color pandoc citations) and the second as link (because you used the square brackets to times).

The only thing you could do is to simply disable the coloring of of Pandoc citations in the style settings, which would also stop the coloring of inline-dataview fields in square brackets.

<img width="1398" alt="Screenshot 2021-10-03 17 56 02" src="https://user-images.githubusercontent.com/73286100/135761934-a2bb85db-cc4d-410c-92b7-da5baeadc752.png">
