### ISSUE TITLE
Feature Request: Reduce the Indention line space so more indents could fit in & easier to work with 

### ISSUE THREAD

**Issue by Droyk** [chrisgrieser/shimmering-focus#270]
### Feature Requested

Provide a way so the user can reduce space b/w the relationship lines so **more** indents could fit in the **live preview**
![image](https://github.com/chrisgrieser/shimmering-focus/assets/15848350/fc9c2203-2c05-49a1-b964-e1bbec68485e)

though in the **Reading mode** it shows them perfectly
![image](https://github.com/chrisgrieser/shimmering-focus/assets/15848350/d564e4cf-4ed2-4116-b160-8befc8ee2b01)

A better way would be to let the user control the space b/w the indents. Provide an option for the user to adjust how far the indent should be from each other, from 1px to 100px. with this precise control I would choose only 1px to 3px coz I like to see them in hierarchy but don't want them to take space coz it hard to read the content if there's a big list down the line. Or just do it like the reading mode does this above. 

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] The feature would be useful to more users than just me. (If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [X] My issue concerns Obsidian version 1.0+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
- [X] This issue concerns the theme in general and is not related to a specific plugin, for which there [is the plugin-support form](https://github.com/chrisgrieser/shimmering-focus/issues/new?template=plugin_support.yml).

**Comment by Droyk** [comment]
Bump, is there any way to do this locally? @chrisgrieser

**Comment by chrisgrieser** [comment]
Hi, sorry for not getting back to this earlier.

Since this theme already has way too many settings, I try to be conservative when it comes to adding more settings. And, I think having *this many* levels of indentation is quite the rare case.  I think your request would be better handled with a local CSS snippet on your end.

I'd ask in the `#appearance` channel of the Obsidian Discord server or the Obsidian forum about it how to create such a snippet, if you are not familiar with it.
