### ISSUE TITLE
[Bug - not vital]: Highlight colors are not carried through to PDF Export

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#39]
Thanks to you the highlight colors finally work in my snippet both in edit and preview mode. When I tried exporting it to PDF just now, I noticed that tthe colors were the default theme colors again.
![highlight](https://user-images.githubusercontent.com/71895400/139841065-3204e1a2-d3c3-458b-94e9-bbebff567c0e.png)

Here are the edit and preview modes, and here is a sample pdf
[test.pdf](https://github.com/chrisgrieser/shimmering-focus/files/7460352/test.pdf)

This is not a rush, just something I noticed :)

**Comment by chrisgrieser** [comment]
oh yes, PDF export is a big area I haven't had the time to look into at all yet. I'll dive into it, but it might take some time, because it's a whole new area to me as well and at least compared to the other things I still want to do with the theme, it's not super high priority.

But when I get to it, I'll look into it :)

**Comment by ReaderGuy42** [comment]
Cool, no rush :)

**Comment by chrisgrieser** [comment]
Hi! sorry for the slow reponses recently, got some work stuff to do and therefore less time for theme and stuff.

Well, the answer is actually pretty easy: you won't find anything in Shimmering Focus that governs the PDF export, since the theme does not include a single line of code that affects PDF export 😅

print has it's very own logic of CSS (need to account for page margins and stuff), and I 100% haven't looked into the subject yet

**Comment by ReaderGuy42** [comment]
(sorry didn't get a notification for your reply)

OK, that's fine, now worries at all, was just curious :)

**Comment by ReaderGuy42** [comment]
Hey, so I solved this :) I realized that the blue bold coloring that you had in the theme at one point and that I still use was showing up correctly in exported PDFs, so I played around with it, and got the following new snippet. I'm not sure how useful this'll be for anyone else, but with this, the highlight colors will export as the same that they show up as in Obsidian itself. Though you'll have to adjust the colors. I use `==yellow`, `**==blue==**, and `*==red==*`, though that was different in the default theme.

```

/* Yellow Highlights for PDF */

.theme-light span.cm-highlight,
.theme-light body > .app-container div.markdown-preview-view mark {
	font-style: initial !important;
	background-color: var(--highlight-yellow);
	color: #222;
}


.theme-light span.cm-highlight,
.theme-light .markdown-preview-view mark {
	font-style: initial !important;
	background-color: var(--highlight-yellow);
	color: #222;
}

/* Blue Highlights for PDF */

.theme-light span.cm-strong.cm-highlight,
.theme-light body > .app-container div.markdown-preview-view strong > mark {
	font-style: initial !important;
	background-color: var(--highlight-blue);
	color: #222;
}


.theme-light span.cm-strong.cm-highlight,
.theme-light .markdown-preview-view strong > mark {
	font-style: initial !important;
	background-color: var(--highlight-blue);
	color: #222;
}

/* Red Highlights for PDF */

.theme-light span.cm-em.cm-highlight,
.theme-light body > .app-container div.markdown-preview-view em > mark {
	font-style: initial !important;
	background-color: var(--highlight-red);
	color: #222;
}


.theme-light span.cm-em.cm-highlight,
.theme-light .markdown-preview-view em > mark {
	font-style: initial !important;
	background-color: var(--highlight-red);
	color: #222;
}

```
I honestly still don't understand about css (or any kind of code) to know _why_ it works, but it does and I'm happy :)

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
