### ISSUE TITLE
Add configurable academic tags to Style Settings plugin

### ISSUE THREAD

**Issue by DeutscheGabanna** [chrisgrieser/shimmering-focus#46]
![image](https://user-images.githubusercontent.com/59067099/141493668-cad4ceab-06c4-4b18-840e-c07d1f33e03a.png)

I wish I could edit the strings triggering each look in the settings instead of the CSS.

**Comment by chrisgrieser** [comment]
unfortunately, this isn't easily possible, since the annotation tags themselves are a bit of an hacky solution. You can, however, use a CSS snippet and add your own style settings if you like. 

You can use this [template for it](https://github.com/chrisgrieser/shimmering-focus/blob/main/annotation-tag-template.css), replace all instances of `#important` and `cm-tag-important` with the tag you want.

**Comment by Gewerd-Strauss** [comment]
> You can use this [template for it](https://github.com/chrisgrieser/shimmering-focus/blob/main/annotation-tag-template.css), replace all instances of `#important` and `cm-tag-important` with the tag you want.

In what path do these templates have to be saved? I don't think it's mentioned anywhere.

**Comment by chrisgrieser** [comment]
@Gewerd-Strauss I added some information to the template on where to save it. basically:
> 4. Save the file as CSS snippet in `{your-vault-path}/.obsidian/snippets`
https://help.obsidian.md/How+to/Add+custom+styles#Use+Themes+and+or+CSS+snippets
> 5. go to Obsidian Settings ➞ Appearance, Reload the snippets and enable the snippet you just saved.
