### ISSUE TITLE
issue: unable to click+drag window to reposition on macOS

### ISSUE THREAD

**Issue by hieu6** [chrisgrieser/shimmering-focus#6]
hello! **love** the theme. 

issue is title above. i'm not sure if i'm missing something, if i should be holding down a shortkey to click + drag to move the obsidian window. i'm just kind of moving it like a caterpillar right now. drag, resize, plop. because i love the theme that much xD

i realize this is your first .css project! if there's somewhere i could poke around to check this out, please let me know, and i'll take a look.

**Comment by chrisgrieser** [comment]
thanks! 

Ah, the moving of windows actually hasn't occurred to me since I use [Moom](https://apps.apple.com/us/app/moom/id419330170?mt=12) to move & resize windows with keyboard shortcuts. 😅

Well, this cannot be addressed without making the titlebar visible again, which would be a setting for when implementing it with the Style Settings Plugin (see issue #2). I am therefore closing this issue, since it will in practice be solved when I have the time to implement changing settings with the Style settings plugin.

However, in the meantime, you can simply remove the following lines of code (line 145-163) from the `.css` file of theme. These will make the titlebar re-appear so you can use the theme until I get around doing the Settings Plugin thing. :)
```
/* hide titlebar */
.titlebar {
	display: none;
}
/* thanks to @SlRvB */
.theme-dark,
.theme-light {
	padding: 0 !important;
}
/* for Mac OS Traffic Lights */
/* same for right side to harmonize */
.workspace-split.mod-left-split > .workspace-tabs,
.workspace-split.mod-right-split > .workspace-tabs {
	padding-top: 1.15em;
}
/* fix height of resize handle */
.workspace-split.mod-horizontal .workspace-leaf-resize-handle {
	top: 3.05em !important;
}
```

**Comment by chrisgrieser** [comment]
With [release 1.4](https://github.com/chrisgrieser/shimmering-focus/releases/tag/1.4), I added support for the [Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings/). Using that plugin, re-enabling the titlebar for moving the window is now simply a mouse click.

This also allows you to install updates of _Shimmering Focus_ without having to search and delete those lines of code again 🙂

**Comment by hieu6** [comment]
hey, thank you so so much for the update! YES
