### ISSUE TITLE
[BUG] Relationship line needs improvement to work with different fonts

### ISSUE THREAD

**Issue by b1uegh0st** [chrisgrieser/shimmering-focus#70]
**Describe the Bug**
To my knowledge you just rework the relationship lines for lists. I think it still needs some improvement. Currently it seems to work on a fix width basis, which doesn't work if changing the font (one of the thing that you strongly support in Style Settings already).

Thanks for a great theme and especially for keeping up with the updates to keep it working.

**To Reproduce**
1. Go to Style Settings, change the font.
2. The number of relationship lines varied for the same set of indent (see screenshots)

**Is the Problem related to Obsidian 0.13+ / Live Preview Mode?**
I tried both Liver Preview and Legacy Editor. The problem persists.

**Relevant Screenshots**

**normal IA Quattro font - default** - 3 lines as expected (3 level of indent)
<img width="70" alt="image" src="https://user-images.githubusercontent.com/6695697/147383032-3bda6cde-c1d8-49bf-978f-0659bb61c0ee.png">

(IBM Plex Sans as main font) - 2 lines
<img width="70" alt="image" src="https://user-images.githubusercontent.com/6695697/147383049-a224946d-91d3-4df7-b0f8-a7152a2935a6.png">

(monofont - IBM Plex Mono as main font) - 4 lines
<img width="113" alt="image" src="https://user-images.githubusercontent.com/6695697/147383109-cc7525ea-cb9a-4ca1-a20e-b24b08cea829.png">

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I checked that the issue does not occur when using the default theme.
- [x] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Ah thanks for reporting this! I haven't noticed it since I do not change my main font. For some reason, iA Writer needs a different indention size than other fonts. (Maybe a bug with their font file? 🤔 )

Anyway, I have added a style setting option to fix this for other font:
<img width="885" alt="Screenshot 2021-12-25 16 00 31" src="https://user-images.githubusercontent.com/73286100/147387861-8f13cd73-a180-496e-a52a-f53f99f62c41.png">

**Comment by b1uegh0st** [comment]
Hi thanks for the fast response, 
 
 It works alright for IBM Plex Sans now (rather a more "normal" font). For using a mono font (IBM Plex Mono, and hence the spacing is increased) as main font there are still some problems of more lines then needed.
 
 I think it is alright to de-prioritize this for now, I can try to live with it. But maybe save this for next time if you want to upgrade the relationship lines approach.

 Thanks,
 NA

**Comment by chrisgrieser** [comment]
Ah, haven't tested for mono fonts. I pushed an update which provides options for monospace and proportional font fixes. Seems like different font types all require specific indention values for the relationship lines to work 🤔 

btw, I am essentially using the CSS from the outliner plugin where I only adjust one value, so I assume they will have the issue as well. Since they are the expert on relationship lines, maybe open up an issue there as well? It's more likely that they will find a solution that works nicely for every font.

**Comment by b1uegh0st** [comment]
Just updated (and tested). You are fast!! It works great! Thanks.

And yes, Outliner plugin is having some issues with the migration to CM6, too (per their control of tab-ing for the whole block, sometimes it works with new editor, sometimes it doesn't work Legacy Editor). So I agree this part of the transition of the process will be a bit tedious.

**Comment by chrisgrieser** [comment]
no problem! fixing this was literally only adjusting one value and modifying the style setting to offer more options :)

yeah, the relationship lines are rather tricky to implement, but I am optimistic that the community will find a good solution soon(ish).

Probably getting all those plugins working in CM6 is the bigger priority for most people. And I am still finding (minor) CM6 bugs in my theme every day 😅
