### ISSUE TITLE
Feature Request: make active pane more distinguishable

### ISSUE THREAD

**Issue by imeed166** [chrisgrieser/shimmering-focus#79]
**Feature Requested**
The color difference between the title of the active pane and the other pane is very small, which makes it a bit hard to know where the active pane is. Maybe make the other pane darker or make the active pane more prominent by changing the title text color to accent color ?

**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/38974541/147968353-d2171e0e-dc5d-4cc5-92f8-146f67902dbc.png)

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
- [x] I have checked that the feature is *not* already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi, that's a good idea. My main problem is, that any method of emphasizing the active pane needs to work with the default settings of the theme, where titlebar and header bar are hidden. And if both are hidden, the options for emphasizing the active pane are limited. :/

And making the inactive panes darker would decrease readability, and you do want to work with both panes after all.

Do you have idea any good idea maybe? because I couldn't come up with a good solution for that one :(

**Comment by imeed166** [comment]
I don't know what is possible with css, but I have 2 ideas :
1. Highlight the border of the active pane (top only/bottom only/ left and right or even the four borders at the same time) whatever looks best. In my opinion, color the tiny top bar of the active pane to gray like the delimiter

https://user-images.githubusercontent.com/38974541/148083173-cf6d3cad-ffc6-4cd1-92c8-9f8db27a9906.mov

2. make 2 background colors, one for the active pane and the other for the inactive panes.

**Comment by chrisgrieser** [comment]
Okay, I made the inactive panes a bit more "shadowy", that should help as well! :)
