### ISSUE TITLE
Question: Pseudo-Admonition gone?

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#87]
I saw the discussion in issue https://github.com/chrisgrieser/shimmering-focus/issues/60 that you had removed the pseudo-admonitions. Are those gone completely? I ask because I see there's still an option for the symbol for the admonitions in Style Settings but that symbol doesn't show up for Header 6.

Thanks :)

**Comment by chrisgrieser** [comment]
They were removed at that point, since they were quite limited and also messed up other plugins using headings (e.g. Outline Plugin).

However, with yesterday's update I cam up with a new, different form of Admonitions that work multi-line and do not mess up heading structures: https://github.com/chrisgrieser/shimmering-focus#multi-line-admonitions

(they are quite hacky, so expect I expect that there are still some bugs for edge cases)

**Comment by ReaderGuy42** [comment]
Thanks!

**Comment by ReaderGuy42** [comment]
Not sure this is worth opening another issue but with the >>> admonitions in Preview mode (legacy and Live Preview) the first letter gets mostly/partially cut off:
![image](https://user-images.githubusercontent.com/71895400/152547861-fc653643-0017-4c79-94da-a96ae60730d4.png)

**Comment by chrisgrieser** [comment]
yeah, that looks like a bug to me, so you should open a separate issue for that.
