### ISSUE TITLE
[Bug]: Line length in mobile

### ISSUE THREAD

**Issue by Cateroo** [chrisgrieser/shimmering-focus#95]
### Bug Description

While using shimmering focus on mobile, it leaves a margin space on the left. 
Fiddling with the max view and line length settings doesn't change this. 

Have attached screenshot to compare width against the default theme. 

### Relevant Screenshot

![Screenshot_20220123-072006](https://user-images.githubusercontent.com/80290663/150671840-161e7dee-076c-4bfb-a8d5-1302dd3d3835.png)
![Screenshot_20220123-071935](https://user-images.githubusercontent.com/80290663/150671845-5e0f59ab-ae89-45c9-9cb5-312f85462d18.png)

### Obsidian Version

1.1.0 (Android)

### Installer Version

1.1.0 (Android)

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [X] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] iOS
- [X] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
Hi! As you may have heard, the upcoming Obsidian update 0.16 has a massive amount of changes for theme development, necessitating a complete rewrite of *Shimmering Focus*. This means:
1. A lot of bugs and feature requests will be obsolete. with Obsidian 0.16 and the rewritten *Shimmering Focus*.
2. As the theme has over 15,000 lines of CSS, the rewriting will take a considerable amount of time. Recreating the core features alone will likely take me a while, so I simply will not have much time to implement many feature requests, since the recreation of the past core features has priority.

Basically, this is the reason why I am – for now – closing this issue. If your bug still exists / your feature request is still relevant in the upcoming version 3.0 of *Shimmering Focus*, please comment here and I will re-open it. 🙂
