### ISSUE TITLE
[Bug]: Checkbox disappears in Live Preview. Checkbox OK with checkbox snippets from other themes.

### ISSUE THREAD

**Issue by ontrou** [chrisgrieser/shimmering-focus#96]
### Bug Description

A minor problem. But I can tell from your documentation that you are meticulous :-)

In Live Preview mode, the task checkbox disappears when the "SlRvb checkbox snippet" (+ compatibility snippet) is used in conjunction with the Tasks plugin.

When I use checkbox snippets from the Sanctum and Ebullient themes instead in Shimmering Focus, I see the expected behaviour (i.e. task checkbox is present).

### Relevant Screenshot

In Daily note:

![checkbox](https://user-images.githubusercontent.com/77127294/150690754-bbf778c0-237d-4003-9ea4-4c573367e058.png)

### To Reproduce

1. Enable SlRvb checkbox and compatibility snippet. 
2. Enable Tasks plugin
3. Display tasks due today in daily note

````
```tasks
due on 2022-01-23
sort by due
hide task count
hide backlink
short mode
```
````

### Obsidian Version

0.13.19

### Installer Version

0.12.19

### Which editor are you using?

- [x] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [ ] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by chrisgrieser** [comment]
> But I can tell from your documentation that you are meticulous :-)

😊 

yeah, the whole custom checkbox thing is indeed incredibly troublesome for all theme developers, which is why I haven't even tried to touch them but only made my theme somewhat compatible with the one from Slr... 😭 

I haven't documented it properly except a short note in the changelog, but I basically deprecated support for Slr's checkboxes, since the [Snippetor plugin](https://github.com/ebullient/obsidian-snippetor) (still in beta) should standardize custom checkboxes, simplifying the issue for theme devs as well as users.

So I recommend that you also switch to the Snippetor plugin. Styling for the plugin right now makes little sense, since it's still in rapid development, but once it's stable, I'll make my theme compatible with – anything else is work that becomes obsolete soon.

Therefore I am closing this issue for now – should the theme still create issues with custom checkboxes when using snippetor's public release, please re-open this issue (or create a new one.) 🙏
